# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/Volume/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/Volume/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingVolumeCxx-ProjectedTetrahedraZoomIn "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "ProjectedTetrahedraZoomIn" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-ProjectedTetrahedraZoomIn PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestFinalColorWindowLevel "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestFinalColorWindowLevel" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestFinalColorWindowLevel.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestFinalColorWindowLevel PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestFixedPointRayCastLightComponents "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestFixedPointRayCastLightComponents" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestFixedPointRayCastLightComponents.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestFixedPointRayCastLightComponents PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastAdditive "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastAdditive" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastAdditive.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastAdditive PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCompositeBinaryMask "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCompositeBinaryMask" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCompositeBinaryMask.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCompositeBinaryMask PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCompositeMaskBlend "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCompositeMaskBlend" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCompositeMaskBlend.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCompositeMaskBlend PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCompositeMask "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCompositeMask" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCompositeMask.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCompositeMask PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCompositeToMIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCompositeToMIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCompositeToMIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCompositeToMIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCropping "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCropping" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCropping.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCropping PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastDataTypesMinIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastDataTypesMinIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastDataTypesMinIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastDataTypesMinIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastDataTypesMIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastDataTypesMIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastDataTypesMIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastDataTypesMIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsComposite "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastFourComponentsComposite" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastFourComponentsComposite.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsComposite PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsCompositeStreaming "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastFourComponentsCompositeStreaming" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastFourComponentsCompositeStreaming.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsCompositeStreaming PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsMinIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastFourComponentsMinIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastFourComponentsMinIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsMinIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsMIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastFourComponentsMIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastFourComponentsMIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsMIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastMapperBenchmark "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastMapperBenchmark" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastMapperBenchmark.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastMapperBenchmark PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastMapperSampleDistance "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastMapperSampleDistance" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastMapperSampleDistance.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastMapperSampleDistance PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastMIPBinaryMask "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastMIPBinaryMask" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastMIPBinaryMask.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastMIPBinaryMask PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastMIPToComposite "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastMIPToComposite" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastMIPToComposite.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastMIPToComposite PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastNearestDataTypesMIP "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastNearestDataTypesMIP" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastNearestDataTypesMIP.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastNearestDataTypesMIP PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastPerspectiveParallel "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastPerspectiveParallel" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastPerspectiveParallel.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastPerspectiveParallel PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeOrientation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeOrientation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeOrientation.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeOrientation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeUpdate "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeUpdate" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeUpdate.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeUpdate PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPUVolumeRayCastMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPUVolumeRayCastMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPUVolumeRayCastMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPUVolumeRayCastMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestMinIntensityRendering "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestMinIntensityRendering" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestMinIntensityRendering.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestMinIntensityRendering PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestProjectedTetrahedra "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestProjectedTetrahedra" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestProjectedTetrahedra.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestProjectedTetrahedra PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestSmartVolumeMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestSmartVolumeMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestSmartVolumeMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestSmartVolumeMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestSmartVolumeMapperWindowLevel "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestSmartVolumeMapperWindowLevel" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestSmartVolumeMapperWindowLevel.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestSmartVolumeMapperWindowLevel PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCameraInside "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCameraInside" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCameraInside.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCameraInside PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCameraInsideSmallSpacing "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCameraInsideSmallSpacing" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCameraInsideSmallSpacing.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCameraInsideSmallSpacing PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCameraInsideTransformation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCameraInsideTransformation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCameraInsideTransformation.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCameraInsideTransformation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastCellData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastCellData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastCellData.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastCellData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastClipping "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastClipping" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastClipping.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastClipping PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastClippingPolyData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastClippingPolyData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastClippingPolyData.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastClippingPolyData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastClippingUserTransform "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastClippingUserTransform" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastClippingUserTransform.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastClippingUserTransform PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastDependentComponentsLightParameters "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastDependentComponentsLightParameters" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastDependentComponentsLightParameters.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastDependentComponentsLightParameters PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsDependentGradient "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastFourComponentsDependentGradient" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastFourComponentsDependentGradient.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastFourComponentsDependentGradient PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastGradientOpacity "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastGradientOpacity" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastGradientOpacity.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastGradientOpacity PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastGradientOpacityLight "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastGradientOpacityLight" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastGradientOpacityLight.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastGradientOpacityLight PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastIndependentComponentsLightParameters "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastIndependentComponentsLightParameters" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastIndependentComponentsLightParameters.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastIndependentComponentsLightParameters PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastIndependentVectorMode "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastIndependentVectorMode" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastIndependentVectorMode.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastIndependentVectorMode PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastLargeColorTransferFunction "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastLargeColorTransferFunction" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastLargeColorTransferFunction.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastLargeColorTransferFunction PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastPositionalLights "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastPositionalLights" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastPositionalLights.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastPositionalLights PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastReleaseResources "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastReleaseResources" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastReleaseResources.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastReleaseResources PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastRenderDepthToImage "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastRenderDepthToImage" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastRenderDepthToImage.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastRenderDepthToImage PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastRenderDepthToImage2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastRenderDepthToImage2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastRenderDepthToImage2.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastRenderDepthToImage2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastRenderToTexture "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastRenderToTexture" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastRenderToTexture.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastRenderToTexture PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastThreeComponentsIndependent "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastThreeComponentsIndependent" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastThreeComponentsIndependent.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastThreeComponentsIndependent PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsDependent "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastTwoComponentsDependent" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastTwoComponentsDependent.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsDependent PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsDependentGradient "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastTwoComponentsDependentGradient" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastTwoComponentsDependentGradient.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsDependentGradient PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsGradient "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastTwoComponentsGradient" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastTwoComponentsGradient.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsGradient PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsIndependent "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastTwoComponentsIndependent" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastTwoComponentsIndependent.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastTwoComponentsIndependent PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeDepthPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeDepthPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeDepthPass.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeDepthPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeLightKit "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeLightKit" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeLightKit.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeLightKit PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumePicking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumePicking" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumePicking.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumePicking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumePolyData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumePolyData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumePolyData.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumePolyData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeRotation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeRotation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeRotation.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeRotation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestGPURayCastVolumeScale "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestGPURayCastVolumeScale" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestGPURayCastVolumeScale.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestGPURayCastVolumeScale PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestProjectedTetrahedraOffscreen "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestProjectedTetrahedraOffscreen" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestProjectedTetrahedraOffscreen.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestProjectedTetrahedraOffscreen PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestProjectedTetrahedraTransform "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestProjectedTetrahedraTransform" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestProjectedTetrahedraTransform.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestProjectedTetrahedraTransform PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
ADD_TEST(vtkRenderingVolumeCxx-TestRemoveVolumeNonCurrentContext "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingVolumeCxxTests" "TestRemoveVolumeNonCurrentContext" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Volume/Testing/Data/Baseline/TestRemoveVolumeNonCurrentContext.png")
SET_TESTS_PROPERTIES(vtkRenderingVolumeCxx-TestRemoveVolumeNonCurrentContext PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingVolume")
