set(vtkCommonCore_LOADED 1)
set(vtkCommonCore_DEPENDS "vtkkwiml;vtksys")
set(vtkCommonCore_LIBRARIES "vtkCommonCore")
set(vtkCommonCore_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Common/Core;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/Common/Core")
set(vtkCommonCore_LIBRARY_DIRS "")
set(vtkCommonCore_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkCommonCore_WRAP_HIERARCHY_FILE "")
set(vtkCommonCore_KIT "vtkCommon")
set(VTK_DEBUG_LEAKS "OFF")
set(VTK_USE_64BIT_IDS "ON")
set(VTK_ALL_NEW_OBJECT_FACTORY "OFF")

