set(vtkexpat_LOADED 1)
set(vtkexpat_DEPENDS "")
set(vtkexpat_LIBRARIES "vtkexpat")
set(vtkexpat_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/expat;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/expat")
set(vtkexpat_LIBRARY_DIRS "")
set(vtkexpat_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkexpat_WRAP_HIERARCHY_FILE "")
set(vtkexpat_KIT "")
set(vtkexpat_EXCLUDE_FROM_WRAPPING 1)

