set(vtkfreetype_LOADED 1)
set(vtkfreetype_DEPENDS "vtkkwiml;vtkzlib")
set(vtkfreetype_LIBRARIES "vtkfreetype")
set(vtkfreetype_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/freetype;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/freetype")
set(vtkfreetype_LIBRARY_DIRS "")
set(vtkfreetype_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkfreetype_WRAP_HIERARCHY_FILE "")
set(vtkfreetype_KIT "")
set(vtkfreetype_EXCLUDE_FROM_WRAPPING 1)

