set(vtkhdf5_LOADED 1)
set(vtkhdf5_DEPENDS "vtkzlib")
set(vtkhdf5_LIBRARIES "vtkhdf5_hl;vtkhdf5")
set(vtkhdf5_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/hdf5/vtkhdf5;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/hdf5/vtkhdf5/hl/src;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/hdf5/vtkhdf5/src;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/hdf5;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/hdf5")
set(vtkhdf5_LIBRARY_DIRS "")
set(vtkhdf5_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkhdf5_WRAP_HIERARCHY_FILE "")
set(vtkhdf5_KIT "")
set(vtkhdf5_EXCLUDE_FROM_WRAPPING 1)

