set(vtkjpeg_LOADED 1)
set(vtkjpeg_DEPENDS "")
set(vtkjpeg_LIBRARIES "vtkjpeg")
set(vtkjpeg_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/jpeg;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/jpeg")
set(vtkjpeg_LIBRARY_DIRS "")
set(vtkjpeg_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkjpeg_WRAP_HIERARCHY_FILE "")
set(vtkjpeg_KIT "")
set(vtkjpeg_EXCLUDE_FROM_WRAPPING 1)

