set(vtkjsoncpp_LOADED 1)
set(vtkjsoncpp_DEPENDS "")
set(vtkjsoncpp_LIBRARIES "vtkjsoncpp")
set(vtkjsoncpp_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/jsoncpp;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/jsoncpp")
set(vtkjsoncpp_LIBRARY_DIRS "")
set(vtkjsoncpp_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkjsoncpp_WRAP_HIERARCHY_FILE "")
set(vtkjsoncpp_KIT "")
set(vtkjsoncpp_EXCLUDE_FROM_WRAPPING 1)

