set(vtklibxml2_LOADED 1)
set(vtklibxml2_DEPENDS "vtkzlib")
set(vtklibxml2_LIBRARIES "vtklibxml2")
set(vtklibxml2_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/libxml2/vtklibxml2;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/libxml2;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/libxml2")
set(vtklibxml2_LIBRARY_DIRS "")
set(vtklibxml2_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtklibxml2_WRAP_HIERARCHY_FILE "")
set(vtklibxml2_KIT "")
set(vtklibxml2_EXCLUDE_FROM_WRAPPING 1)

