set(vtklibproj4_LOADED 1)
set(vtklibproj4_DEPENDS "")
set(vtklibproj4_LIBRARIES "vtkproj4")
set(vtklibproj4_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/libproj4/vtklibproj4;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/libproj4/vtklibproj4;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/libproj4;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/libproj4")
set(vtklibproj4_LIBRARY_DIRS "")
set(vtklibproj4_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtklibproj4_WRAP_HIERARCHY_FILE "")
set(vtklibproj4_KIT "")
set(vtklibproj4_EXCLUDE_FROM_WRAPPING 1)

