set(vtkMetaIO_LOADED 1)
set(vtkMetaIO_DEPENDS "vtkzlib")
set(vtkMetaIO_LIBRARIES "vtkmetaio")
set(vtkMetaIO_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Utilities/MetaIO/vtkmetaio;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Utilities/MetaIO;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/Utilities/MetaIO")
set(vtkMetaIO_LIBRARY_DIRS "")
set(vtkMetaIO_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkMetaIO_WRAP_HIERARCHY_FILE "")
set(vtkMetaIO_KIT "")
set(vtkMetaIO_EXCLUDE_FROM_WRAPPING 1)

