set(vtknetcdf_LOADED 1)
set(vtknetcdf_DEPENDS "vtkhdf5")
set(vtknetcdf_LIBRARIES "vtkNetCDF;vtkNetCDF_cxx")
set(vtknetcdf_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/netcdf/vtknetcdf/include;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/netcdf/vtknetcdf;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/netcdf;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/netcdf")
set(vtknetcdf_LIBRARY_DIRS "")
set(vtknetcdf_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtknetcdf_WRAP_HIERARCHY_FILE "")
set(vtknetcdf_KIT "")
set(vtknetcdf_EXCLUDE_FROM_WRAPPING 1)

