set(vtkoggtheora_LOADED 1)
set(vtkoggtheora_DEPENDS "")
set(vtkoggtheora_LIBRARIES "vtkoggtheora")
set(vtkoggtheora_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/oggtheora;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/oggtheora")
set(vtkoggtheora_LIBRARY_DIRS "")
set(vtkoggtheora_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkoggtheora_WRAP_HIERARCHY_FILE "")
set(vtkoggtheora_KIT "")
set(vtkoggtheora_EXCLUDE_FROM_WRAPPING 1)

