set(vtkRenderingFreeType_LOADED 1)
set(vtkRenderingFreeType_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkFiltersGeneral;vtkRenderingCore;vtkRenderingCore;vtkfreetype")
set(vtkRenderingFreeType_LIBRARIES "vtkRenderingFreeType")
set(vtkRenderingFreeType_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/FreeType;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/FreeType")
set(vtkRenderingFreeType_LIBRARY_DIRS "")
set(vtkRenderingFreeType_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkRenderingFreeType_WRAP_HIERARCHY_FILE "")
set(vtkRenderingFreeType_KIT "vtkRendering")
set(vtkRenderingFreeType_IMPLEMENTS "vtkRenderingCore")

