set(vtktiff_LOADED 1)
set(vtktiff_DEPENDS "vtkjpeg;vtkzlib")
set(vtktiff_LIBRARIES "vtktiff")
set(vtktiff_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/tiff/vtktiff/libtiff;/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/tiff;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/tiff")
set(vtktiff_LIBRARY_DIRS "")
set(vtktiff_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtktiff_WRAP_HIERARCHY_FILE "")
set(vtktiff_KIT "")
set(vtktiff_EXCLUDE_FROM_WRAPPING 1)

