set(vtkTestingGenericBridge_LOADED 1)
set(vtkTestingGenericBridge_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMisc")
set(vtkTestingGenericBridge_LIBRARIES "vtkTestingGenericBridge")
set(vtkTestingGenericBridge_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/GenericBridge;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/Testing/GenericBridge")
set(vtkTestingGenericBridge_LIBRARY_DIRS "")
set(vtkTestingGenericBridge_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkTestingGenericBridge_WRAP_HIERARCHY_FILE "")
set(vtkTestingGenericBridge_KIT "")
set(vtkTestingGenericBridge_EXCLUDE_FROM_WRAPPING 1)

