set(vtkTestingCore_LOADED 1)
set(vtkTestingCore_DEPENDS "vtkCommonCore")
set(vtkTestingCore_LIBRARIES "vtkCommonCore")
set(vtkTestingCore_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Core;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/Testing/Core")
set(vtkTestingCore_LIBRARY_DIRS "")
set(vtkTestingCore_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkTestingCore_WRAP_HIERARCHY_FILE "")
set(vtkTestingCore_KIT "")
set(vtkTestingCore_EXCLUDE_FROM_WRAPPING 1)

