set(vtkzlib_LOADED 1)
set(vtkzlib_DEPENDS "")
set(vtkzlib_LIBRARIES "vtkzlib")
set(vtkzlib_INCLUDE_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ThirdParty/zlib;/home/mike/PCL-Tests/meshGeneration/vtk/VTK/ThirdParty/zlib")
set(vtkzlib_LIBRARY_DIRS "")
set(vtkzlib_RUNTIME_LIBRARY_DIRS "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/lib")
set(vtkzlib_WRAP_HIERARCHY_FILE "")
set(vtkzlib_KIT "")
set(vtkzlib_EXCLUDE_FROM_WRAPPING 1)

