# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Interaction/Widgets/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Interaction/Widgets/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkInteractionWidgetsCxx-BoxWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "BoxWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/BoxWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-BoxWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-BoxWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "BoxWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/BoxWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-BoxWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-ImagePlaneWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "ImagePlaneWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/ImagePlaneWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-ImagePlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TerrainPolylineEditor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TerrainPolylineEditor" "-ProjectionMode" "2" "-HeightOffset" "100" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TerrainPolylineEditor.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TerrainPolylineEditor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets" TIMEOUT "90")
ADD_TEST(vtkInteractionWidgetsCxx-TestAffineWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAffineWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAffineWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestAffineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestAngleWidget2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAngleWidget2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAngleWidget2D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestAngleWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestAngleWidget3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestAngleWidget3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestAngleWidget3D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestAngleWidget3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestBalloonWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBalloonWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBalloonWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestBalloonWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestBiDimensionalWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBiDimensionalWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBiDimensionalWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestBiDimensionalWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestBorderWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBorderWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBorderWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestBorderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestBrokenLineWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestBrokenLineWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestBrokenLineWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestBrokenLineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestCameraWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCameraWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCameraWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestCameraWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestCaptionWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCaptionWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCaptionWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestCaptionWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestCellCentersPointPlacer "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCellCentersPointPlacer" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCellCentersPointPlacer.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestCellCentersPointPlacer PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestCenteredSliderWidget2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCenteredSliderWidget2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCenteredSliderWidget2D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestCenteredSliderWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestCheckerboardWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestCheckerboardWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestCheckerboardWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestCheckerboardWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestConstrainedHandleWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestConstrainedHandleWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestConstrainedHandleWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestConstrainedHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestContourWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestContourWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestContourWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestContourWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestDijkstraImageGeodesicPath "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDijkstraImageGeodesicPath" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDijkstraImageGeodesicPath.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestDijkstraImageGeodesicPath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestDistanceWidget3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDistanceWidget3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDistanceWidget3D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestDistanceWidget3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestDistanceWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDistanceWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDistanceWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestDistanceWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestFinitePlaneWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFinitePlaneWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFinitePlaneWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestFinitePlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestFixedSizeHandleRepresentation3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFixedSizeHandleRepresentation3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFixedSizeHandleRepresentation3D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestFixedSizeHandleRepresentation3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestFocalPlaneContour "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestFocalPlaneContour" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestFocalPlaneContour.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestFocalPlaneContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestHandleWidget2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestHandleWidget2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestHandleWidget2D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestHandleWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestHandleWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestHandleWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestHandleWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImageActorContourWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImageActorContourWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImageActorContourWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImageActorContourWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImageTracerWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImageTracerWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImageTracerWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImageTracerWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitCylinderWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitCylinderWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitCylinderWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitCylinderWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitCylinderWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2b "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2b" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2b.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2b PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget3 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget3" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget3.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2LockNormalToCamera "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget2LockNormalToCamera" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget2LockNormalToCamera.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget2LockNormalToCamera PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestImplicitPlaneWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestImplicitPlaneWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestImplicitPlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestLogoWidgetAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidgetAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidgetAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestLogoWidgetAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestLogoWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestLogoWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestLogoWidgetDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLogoWidgetDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLogoWidgetDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestLogoWidgetDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestMultipleViewports "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestMultipleViewports" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestMultipleViewports.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestMultipleViewports PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientationMarkerWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientationMarkerWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientationMarkerWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientationMarkerWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestOrientationMarkerWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestOrthoPlanes "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrthoPlanes" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrthoPlanes.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestOrthoPlanes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestParallelopipedWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestParallelopipedWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestParallelopipedWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestParallelopipedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPickingManagerSeedWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPickingManagerSeedWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPickingManagerSeedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets" TIMEOUT "60")
ADD_TEST(vtkInteractionWidgetsCxx-TestPlaybackWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPlaybackWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPlaybackWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPlaybackWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPointHandleRepresentation3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPointHandleRepresentation3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPointHandleRepresentation3D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPointHandleRepresentation3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestProgrammaticPlacement "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProgrammaticPlacement" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestProgrammaticPlacement.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestProgrammaticPlacement PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestProgressBarWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProgressBarWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestProgressBarWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestProgressBarWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestProp3DButtonRepresentation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestProp3DButtonRepresentation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestProp3DButtonRepresentation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestRectilinearWipeWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestRectilinearWipeWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestRectilinearWipeWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestRectilinearWipeWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestResliceCursorWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestResliceCursorWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestResliceCursorWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestResliceCursorWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestResliceCursorWidget3 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestResliceCursorWidget3" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestResliceCursorWidget3.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestResliceCursorWidget3 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestScalarBarWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestScalarBarWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestScalarBarWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestScalarBarWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSeedWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSeedWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSeedWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSeedWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSeedWidgetNonUniformRepresentations "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSeedWidgetNonUniformRepresentations" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSeedWidgetNonUniformRepresentations.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSeedWidgetNonUniformRepresentations PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSliderWidget2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSliderWidget2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSliderWidget2D.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSliderWidget2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSliderWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSliderWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSliderWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSliderWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSplineWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSplineWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSplineWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSplineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSphereWidgetZoomInOut "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereWidgetZoomInOut" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereWidgetZoomInOut.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSphereWidgetZoomInOut PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSphereWidget2CenterCursor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereWidget2CenterCursor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereWidget2CenterCursor.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSphereWidget2CenterCursor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestTextWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestTextWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestTextWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestTextWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkAngleRepresentation2DTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleRepresentation2DTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkAngleRepresentation2DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkAngleRepresentation3DTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleRepresentation3DTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkAngleRepresentation3DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkAngleWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkAngleWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkAngleWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkBalloonRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBalloonRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkBalloonRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkBalloonWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBalloonWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkBalloonWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkBiDimensionalRepresentation2DTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBiDimensionalRepresentation2DTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkBiDimensionalRepresentation2DTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkBiDimensionalWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBiDimensionalWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkBiDimensionalWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkBorderWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkBorderWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkBorderWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkCaptionRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkCaptionRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkCaptionRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkCaptionWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkCaptionWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkCaptionWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkConstrainedPointHandleRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkConstrainedPointHandleRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkConstrainedPointHandleRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkHoverWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkHoverWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkHoverWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkLineRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkLineRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkLineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkLineWidget2Test1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkLineWidget2Test1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkLineWidget2Test1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkPolyLineRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkPolyLineRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkPolyLineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkPolyLineWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkPolyLineWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkPolyLineWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkSeedRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSeedRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkSeedRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkSeedWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSeedWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkSeedWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkSplineRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSplineRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkSplineRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkSplineWidget2Test1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkSplineWidget2Test1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkSplineWidget2Test1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkTextRepresentationTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkTextRepresentationTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkTextRepresentationTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-vtkTextWidgetTest1 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "vtkTextWidgetTest1" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-vtkTextWidgetTest1 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestDijkstraGraphGeodesicPath "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestDijkstraGraphGeodesicPath" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestDijkstraGraphGeodesicPath.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestDijkstraGraphGeodesicPath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestLineWidget2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLineWidget2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLineWidget2.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestLineWidget2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestLineWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestLineWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestLineWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestLineWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestOrientedGlyphContour "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestOrientedGlyphContour" "--PlaybackFile" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Input/TestOrientedGlyphContourEventLog.txt" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestOrientedGlyphContour.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestOrientedGlyphContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPlaneWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPlaneWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPlaneWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPlaneWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPointWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPointWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPointWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPointWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPolygonalHandleRepresentations "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalHandleRepresentations" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalHandleRepresentations.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPolygonalHandleRepresentations PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPolygonalRepresentationHandleWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalRepresentationHandleWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalRepresentationHandleWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPolygonalRepresentationHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPolygonalSurfaceConstrainedDistanceWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolygonalSurfaceConstrainedDistanceWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPolygonalSurfaceConstrainedDistanceWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPolygonalSurfaceConstrainedDistanceWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPolyPlane "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPolyPlane" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPolyPlane PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestSphereHandleWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSphereHandleWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSphereHandleWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSphereHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets" RUN_SERIAL "ON" TIMEOUT "300")
ADD_TEST(vtkInteractionWidgetsCxx-TestSurfaceConstrainedHandleWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestSurfaceConstrainedHandleWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestSurfaceConstrainedHandleWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestSurfaceConstrainedHandleWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestTensorProbeWidget "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestTensorProbeWidget" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestTensorProbeWidget.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestTensorProbeWidget PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
ADD_TEST(vtkInteractionWidgetsCxx-TestPickingManagerWidgets "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkInteractionWidgetsCxxTests" "TestPickingManagerWidgets" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Interaction/Widgets/Testing/Data/Baseline/TestPickingManagerWidgets.png")
SET_TESTS_PROPERTIES(vtkInteractionWidgetsCxx-TestPickingManagerWidgets PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkInteractionWidgets")
