# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Charts/Core/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Charts/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkChartsCoreCxx-TestContextScene "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextScene" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextScene PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestControlPointsItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestControlPointsItem" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestControlPointsItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestControlPointsItemEvents "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestControlPointsItemEvents" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestControlPointsItemEvents PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestAreaPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestAreaPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestAreaPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestAreaPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestAxes "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestAxes" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestAxes.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestAxes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestBagPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestBagPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestBagPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestBagPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestBarGraph "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestBarGraph" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestBarGraph.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestBarGraph PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestBarGraphHorizontal "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestBarGraphHorizontal" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestBarGraphHorizontal.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestBarGraphHorizontal PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestBarGraphSelection "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestBarGraphSelection" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestBarGraphSelection.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestBarGraphSelection PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestBoxPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestBoxPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestBoxPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestBoxPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestCategoryLegend "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestCategoryLegend" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestCategoryLegend.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestCategoryLegend PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestColorTransferFunction "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestColorTransferFunction" "-E" "80" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestColorTransferFunction.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestColorTransferFunction PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartDouble "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartDouble" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartDouble.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartDouble PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartDoubleColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartDoubleColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartDoubleColors.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartDoubleColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartMatrix "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartMatrix" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartMatrix.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartMatrix PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartTileScaling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartTileScaling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartTileScaling.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartTileScaling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartUnicode "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartUnicode" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Fonts/DejaVuSans.ttf" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartUnicode.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartUnicode PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartsOn3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartsOn3D" "-E" "16" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartsOn3D.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartsOn3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartXYInvertedAxis "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartXYInvertedAxis" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartXYInvertedAxis.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartXYInvertedAxis PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestChartXYZ "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestChartXYZ" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestChartXYZ.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestChartXYZ PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContext "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContext" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContext.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContext PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextArea "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextArea" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextArea.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextArea PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextAreaFixedAspect "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextAreaFixedAspect" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextAreaFixedAspect.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextAreaFixedAspect PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextAreaFixedMargins "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextAreaFixedMargins" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextAreaFixedMargins.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextAreaFixedMargins PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextAreaFixedRect "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextAreaFixedRect" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextAreaFixedRect.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextAreaFixedRect PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextImage "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextImage" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextImage.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextImage PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextItemStacking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextItemStacking" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextItemStacking.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextItemStacking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestContextUnicode "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestContextUnicode" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Fonts/DejaVuSans.ttf" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestContextUnicode.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestContextUnicode PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestControlPointsHandleItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestControlPointsHandleItem" "-E" "30" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestControlPointsHandleItem.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestControlPointsHandleItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestDiagram "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestDiagram" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestDiagram.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestDiagram PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestFunctionalBagPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestFunctionalBagPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestFunctionalBagPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestFunctionalBagPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestHistogram2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestHistogram2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestHistogram2D.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestHistogram2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestInteractiveChartXYZ "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestInteractiveChartXYZ" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestInteractiveChartXYZ.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestInteractiveChartXYZ PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLegendHiddenPlots "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLegendHiddenPlots" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLegendHiddenPlots.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLegendHiddenPlots PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlot" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotDouble "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotDouble" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotDouble.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotDouble PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotDouble2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotDouble2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotDouble2.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotDouble2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlot3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlot3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlot3D.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlot3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotAxisFonts "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotAxisFonts" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotAxisFonts.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotAxisFonts PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlot2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlot2" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlot2.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlot2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotInteraction "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotInteraction" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotInteraction.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotInteraction PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotSelection "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotSelection" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotSelection.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotSelection PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestLinePlotSelection2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestLinePlotSelection2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestLinePlotSelection2.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestLinePlotSelection2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestMultipleChartRenderers "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestMultipleChartRenderers" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestMultipleChartRenderers.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestMultipleChartRenderers PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestMultipleRenderers "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestMultipleRenderers" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestMultipleRenderers.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestMultipleRenderers PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestMultipleScalarsToColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestMultipleScalarsToColors" "-E" "25" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestMultipleScalarsToColors.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestMultipleScalarsToColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestParallelCoordinates "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestParallelCoordinates" "-E" "15" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestParallelCoordinates.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestParallelCoordinates PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestParallelCoordinatesDouble "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestParallelCoordinatesDouble" "-E" "15" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestParallelCoordinatesDouble.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestParallelCoordinatesDouble PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestPieChart "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestPieChart" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestPieChart.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestPieChart PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestPlotMatrix "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestPlotMatrix" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestPlotMatrix.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestPlotMatrix PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestPropItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestPropItem" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestPropItem.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestPropItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScalarsToColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScalarsToColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScalarsToColors.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScalarsToColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScatterPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScatterPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScatterPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScatterPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScatterPlotMatrix "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScatterPlotMatrix" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScatterPlotMatrix.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScatterPlotMatrix PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScatterPlotMatrixVehicles "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScatterPlotMatrixVehicles" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScatterPlotMatrixVehicles.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScatterPlotMatrixVehicles PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScatterPlotMatrixVisible "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScatterPlotMatrixVisible" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScatterPlotMatrixVisible.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScatterPlotMatrixVisible PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestScientificPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestScientificPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestScientificPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestScientificPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestStackedBarGraph "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestStackedBarGraph" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestStackedBarGraph.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestStackedBarGraph PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestStackedPlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestStackedPlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestStackedPlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestStackedPlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestSurfacePlot "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestSurfacePlot" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestSurfacePlot.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestSurfacePlot PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
ADD_TEST(vtkChartsCoreCxx-TestZoomAxis "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkChartsCoreCxxTests" "TestZoomAxis" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Charts/Core/Testing/Data/Baseline/TestZoomAxis.png")
SET_TESTS_PROPERTIES(vtkChartsCoreCxx-TestZoomAxis PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkChartsCore")
