# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Filters/HyperTree/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Filters/HyperTree/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkFiltersHyperTreeCxx-TestClipHyperOctree "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestClipHyperOctree" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestClipHyperOctree.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestClipHyperOctree PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperOctreeContourFilter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperOctreeContourFilter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperOctreeContourFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperOctreeContourFilter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperOctreeCutter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperOctreeCutter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperOctreeCutter.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperOctreeCutter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperOctreeDual "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperOctreeDual" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperOctreeDual.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperOctreeDual PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperOctreeSurfaceFilter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperOctreeSurfaceFilter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperOctreeSurfaceFilter.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperOctreeSurfaceFilter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperOctreeToUniformGrid "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperOctreeToUniformGrid" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperOctreeToUniformGrid.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperOctreeToUniformGrid PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2D.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DIJK "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DIJK" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DIJK.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DIJK PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterialIJK "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinary2DMaterialIJK" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinary2DMaterialIJK.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinary2DMaterialIJK PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryEllipseMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinaryEllipseMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinaryEllipseMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryEllipseMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryHyperbolicParaboloidMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridBinaryHyperbolicParaboloidMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridBinaryHyperbolicParaboloidMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridBinaryHyperbolicParaboloidMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2D.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterialBits "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DMaterialBits" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DMaterialBits.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DFullMaterialBits "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DFullMaterialBits" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DFullMaterialBits.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DFullMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DBiMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary2DBiMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary2DBiMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary2DBiMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCut "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisCut" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisCut.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCut PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCutMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DAxisCutMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DAxisCutMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DAxisCutMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContour "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DContour" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DContour.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContour PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContourMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DContourMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DContourMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DContourMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DClip "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DClip" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DClip.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DClip PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCut "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DCut" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DCut.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DCut PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometry "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometry" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometry.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometry PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterialBits "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryMaterialBits" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryMaterialBits.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryLargeMaterialBits "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DGeometryLargeMaterialBits" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DGeometryLargeMaterialBits.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DGeometryLargeMaterialBits PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructured "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DUnstructured" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DUnstructured.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructured PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructuredMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernary3DUnstructuredMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernary3DUnstructuredMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernary3DUnstructuredMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernaryHyperbola "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernaryHyperbola" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernaryHyperbola.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernaryHyperbola PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
ADD_TEST(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterial "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkFiltersHyperTreeCxxTests" "TestHyperTreeGridTernarySphereMaterial" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Filters/HyperTree/Testing/Data/Baseline/TestHyperTreeGridTernarySphereMaterial.png")
SET_TESTS_PROPERTIES(vtkFiltersHyperTreeCxx-TestHyperTreeGridTernarySphereMaterial PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkFiltersHyperTree")
