# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/GL2PSOpenGL2/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/GL2PSOpenGL2/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingGL2PSOpenGL2CxxTests" "TestGL2PSAddPolyPrimitive" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingGL2PSOpenGL2")
ADD_TEST(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive-RasterizePNG "/usr/bin/cmake" "-DPSFILE=/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary/TestGL2PSAddPolyPrimitive.ps" "-DPNGFILE=/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary/TestGL2PSAddPolyPrimitive-raster.png" "-DGS_EXECUTABLE=/usr/bin/gs" "-DREMOVEPS=1" "-P" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK/CMake/RasterizePostScript.cmake")
SET_TESTS_PROPERTIES(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive-RasterizePNG PROPERTIES  DEPENDS "vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive" LABELS "vtkRenderingGL2PSOpenGL2" REQUIRED_FILES "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary/TestGL2PSAddPolyPrimitive.ps")
ADD_TEST(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive-VerifyRasterizedPNG "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingGL2PSOpenGL2CxxTests" "PNGCompare" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-E" "15" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/GL2PSOpenGL2/Testing/Data/Baseline/TestGL2PSAddPolyPrimitive-rasterRef.png" "--test-file" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary/TestGL2PSAddPolyPrimitive-raster.png")
SET_TESTS_PROPERTIES(vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive-VerifyRasterizedPNG PROPERTIES  DEPENDS "vtkRenderingGL2PSOpenGL2Cxx-TestGL2PSAddPolyPrimitive-RasterizePNG" LABELS "vtkRenderingGL2PSOpenGL2" REQUIRED_FILES "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary/TestGL2PSAddPolyPrimitive-raster.png")
