# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Domains/Chemistry/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Domains/Chemistry/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkDomainsChemistryCxx-TestBallAndStick "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestBallAndStick" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBallAndStick.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBallAndStick PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestPDBBallAndStick "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestPDBBallAndStick" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestPDBBallAndStick.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestPDBBallAndStick PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry" RUN_SERIAL "ON" TIMEOUT "360")
ADD_TEST(vtkDomainsChemistryCxx-TestBondColorModeDiscreteByAtom "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestBondColorModeDiscreteByAtom" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBondColorModeDiscreteByAtom.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBondColorModeDiscreteByAtom PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestBondColorModeSingleColor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestBondColorModeSingleColor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestBondColorModeSingleColor.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestBondColorModeSingleColor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestCompositeRender "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestCompositeRender" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestCompositeRender.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestCompositeRender PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestCustomArrayRadius "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestCustomArrayRadius" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestCustomArrayRadius.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestCustomArrayRadius PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestFastRender "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestFastRender" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestFastRender.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestFastRender PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestLiquoriceSticks "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestLiquoriceSticks" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestLiquoriceSticks.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestLiquoriceSticks PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMolecule "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMolecule" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMolecule PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMoleculeIOLegacy "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMoleculeIOLegacy" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMoleculeIOLegacy.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMoleculeIOLegacy PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMoleculeSelection "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMoleculeSelection" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMoleculeSelection PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMoleculeMapperPropertyUpdate "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMoleculeMapperPropertyUpdate" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMoleculeMapperPropertyUpdate.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMoleculeMapperPropertyUpdate PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMultiCylinderOn "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMultiCylinderOn" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMultiCylinderOn.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMultiCylinderOn PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestMultiCylinderOff "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestMultiCylinderOff" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestMultiCylinderOff.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestMultiCylinderOff PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestPeriodicTable "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestPeriodicTable" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestPeriodicTable PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestProgrammableElectronicData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestProgrammableElectronicData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestProgrammableElectronicData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestProteinRibbon "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestProteinRibbon" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestProteinRibbon.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestProteinRibbon PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestSimpleBondPerceiver "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestSimpleBondPerceiver" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestSimpleBondPerceiver PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestVASPAnimationReader "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestVASPAnimationReader" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/VASP/NPT_Z_ANIMATE.out" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestVASPAnimationReader.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestVASPAnimationReader PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestVASPTessellationReader "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestVASPTessellationReader" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/VASP/NPT_Z_TESSELLATE.out" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestVASPTessellationReader.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestVASPTessellationReader PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestVDWSpheres "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestVDWSpheres" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestVDWSpheres.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestVDWSpheres PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
ADD_TEST(vtkDomainsChemistryCxx-TestCMLMoleculeReader "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkDomainsChemistryCxxTests" "TestCMLMoleculeReader" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Domains/Chemistry/Testing/Data/Baseline/TestCMLMoleculeReader.png")
SET_TESTS_PROPERTIES(vtkDomainsChemistryCxx-TestCMLMoleculeReader PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkDomainsChemistry")
