# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/OpenGL2/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/OpenGL2/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingOpenGL2Cxx-TestAppleBug "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestAppleBug" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestAppleBug.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestAppleBug PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestBlurAndSobelPasses "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestBlurAndSobelPasses" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestBlurAndSobelPasses.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestBlurAndSobelPasses PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestCoincident "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestCoincident" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestCoincident.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestCoincident PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestCompositePolyDataMapper2Spheres "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestCompositePolyDataMapper2Spheres" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestCompositePolyDataMapper2Spheres.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestCompositePolyDataMapper2Spheres PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestCubeMap "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestCubeMap" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestCubeMap.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestCubeMap PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestDepthOfFieldPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestDepthOfFieldPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestDepthOfFieldPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestDepthOfFieldPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestDepthPeelingPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestDepthPeelingPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestDepthPeelingPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestDepthPeelingPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestEDLPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestEDLPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestEDLPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestEDLPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestFXAAFilter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestFXAAFilter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestFXAAFilter.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestFXAAFilter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestGaussianBlurPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestGaussianBlurPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestGaussianBlurPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestGaussianBlurPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestLightingMapLuminancePass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestLightingMapLuminancePass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestLightingMapLuminancePass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestLightingMapLuminancePass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestLightingMapNormalsPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestLightingMapNormalsPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestLightingMapNormalsPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestLightingMapNormalsPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestPointFillPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestPointFillPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestPointFillPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestPointFillPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestPointGaussianMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestPointGaussianMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestPointGaussianMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestPointGaussianMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestPointGaussianMapperOpacity "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestPointGaussianMapperOpacity" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestPointGaussianMapperOpacity.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestPointGaussianMapperOpacity PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestRemoveActorNonCurrentContext "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestRemoveActorNonCurrentContext" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestRemoveActorNonCurrentContext.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestRemoveActorNonCurrentContext PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestRenderToImage "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestRenderToImage" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestRenderToImage.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestRenderToImage PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestSSAAPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestSSAAPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestSSAAPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestSSAAPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestSetZBuffer "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestSetZBuffer" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestSetZBuffer.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestSetZBuffer PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestShadowMapBakerPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestShadowMapBakerPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestShadowMapBakerPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestShadowMapBakerPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestShadowMapPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestShadowMapPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestShadowMapPass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestShadowMapPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestSobelGradientMagnitudePass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestSobelGradientMagnitudePass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestSobelGradientMagnitudePass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestSobelGradientMagnitudePass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestSpherePoints "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestSpherePoints" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestSpherePoints.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestSpherePoints PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestUserShader "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestUserShader" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestUserShader.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestUserShader PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestUserShader2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestUserShader2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestUserShader2.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestUserShader2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestVBOPLYMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestVBOPLYMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestVBOPLYMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestVBOPLYMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestVBOPointsLines "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestVBOPointsLines" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestVBOPointsLines.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestVBOPointsLines PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestValuePass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestValuePass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestValuePass.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestValuePass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
ADD_TEST(vtkRenderingOpenGL2Cxx-TestValuePass2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingOpenGL2CxxTests" "TestValuePass2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/OpenGL2/Testing/Data/Baseline/TestValuePass2.png")
SET_TESTS_PROPERTIES(vtkRenderingOpenGL2Cxx-TestValuePass2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingOpenGL2")
