# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Views/Infovis/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Views/Infovis/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkViewsInfovisCxx-TestConeLayoutStrategy "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestConeLayoutStrategy" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestConeLayoutStrategy.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestConeLayoutStrategy PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestCoincidentGraphLayoutView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestCoincidentGraphLayoutView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestCoincidentGraphLayoutView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestCoincidentGraphLayoutView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestColumnTree "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestColumnTree" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestColumnTree.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestColumnTree PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestDendrogramItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestDendrogramItem" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestDendrogramItem.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestDendrogramItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestGraphLayoutView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestGraphLayoutView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestGraphLayoutView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestGraphLayoutView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestHeatmapCategoryLegend "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestHeatmapCategoryLegend" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestHeatmapCategoryLegend.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestHeatmapCategoryLegend PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestHeatmapItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestHeatmapItem" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestHeatmapItem.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestHeatmapItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestHeatmapScalarLegend "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestHeatmapScalarLegend" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestHeatmapScalarLegend.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestHeatmapScalarLegend PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestHierarchicalGraphView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestHierarchicalGraphView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestHierarchicalGraphView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestHierarchicalGraphView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestIcicleView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestIcicleView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestIcicleView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestIcicleView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestIconGlyphFilter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestIconGlyphFilter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestIconGlyphFilter.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestIconGlyphFilter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestInteractorStyleTreeMapHover "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestInteractorStyleTreeMapHover" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestInteractorStyleTreeMapHover.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestInteractorStyleTreeMapHover PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestNetworkViews "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestNetworkViews" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestNetworkViews.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestNetworkViews PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestParallelCoordinatesView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestParallelCoordinatesView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestParallelCoordinatesView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestParallelCoordinatesView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestRenderView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestRenderView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestRenderView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestRenderView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestSpanTreeLayoutStrategy "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestSpanTreeLayoutStrategy" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestSpanTreeLayoutStrategy.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestSpanTreeLayoutStrategy PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestTanglegramItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestTanglegramItem" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestTanglegramItem.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestTanglegramItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestTreeHeatmapAutoCollapse "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestTreeHeatmapAutoCollapse" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestTreeHeatmapAutoCollapse.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestTreeHeatmapAutoCollapse PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestTreeHeatmapItem "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestTreeHeatmapItem" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestTreeHeatmapItem.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestTreeHeatmapItem PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestTreeMapView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestTreeMapView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestTreeMapView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestTreeMapView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
ADD_TEST(vtkViewsInfovisCxx-TestTreeRingView "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkViewsInfovisCxxTests" "TestTreeRingView" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Views/Infovis/Testing/Data/Baseline/TestTreeRingView.png")
SET_TESTS_PROPERTIES(vtkViewsInfovisCxx-TestTreeRingView PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkViewsInfovis")
