# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/FreeType/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/FreeType/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingFreeTypeCxx-TestFTStringToPath "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestFTStringToPath" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestFTStringToPath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestFTStringToPath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestFreeTypeTextMapperNoMath "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestFreeTypeTextMapperNoMath" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Fonts/DejaVuSans.ttf" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestFreeTypeTextMapperNoMath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestFreeTypeTextMapperNoMath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestFreeTypeTools "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestFreeTypeTools" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestFreeTypeTools PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestMathTextFreeTypeTextRendererNoMath "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestMathTextFreeTypeTextRendererNoMath" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Fonts/DejaVuSans.ttf" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestMathTextFreeTypeTextRendererNoMath.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestMathTextFreeTypeTextRendererNoMath PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:" LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3D.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3D PROPERTIES  FAIL_REGULAR_EXPRESSION "ERROR:" LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActorAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActorAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActorAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActorAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActorDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActorDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActorDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActorDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3DAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3DAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3DAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3DAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActor3DDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActor3DDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActor3DDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActor3DDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextActorScaleModeProp "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextActorScaleModeProp" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextActorScaleModeProp.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextActorScaleModeProp PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
ADD_TEST(vtkRenderingFreeTypeCxx-TestTextMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingFreeTypeCxxTests" "TestTextMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/FreeType/Testing/Data/Baseline/TestTextMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingFreeTypeCxx-TestTextMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingFreeType")
