# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/Core/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/Core/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2Picking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2Picking" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2Picking.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2Picking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2Scalars "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2Scalars" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2Scalars.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2Scalars PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2CellScalars "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2CellScalars" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2CellScalars.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2CellScalars PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2MixedGeometryCellScalars "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2MixedGeometryCellScalars" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2MixedGeometryCellScalars.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2MixedGeometryCellScalars PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestCompositePolyDataMapper2MixedGeometryEdges "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestCompositePolyDataMapper2MixedGeometryEdges" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestCompositePolyDataMapper2MixedGeometryEdges.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestCompositePolyDataMapper2MixedGeometryEdges PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestMultiBlockPartialArrayPointData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestMultiBlockPartialArrayPointData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestMultiBlockPartialArrayPointData.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestMultiBlockPartialArrayPointData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestMultiBlockPartialArrayFieldData "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestMultiBlockPartialArrayFieldData" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestMultiBlockPartialArrayFieldData.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestMultiBlockPartialArrayFieldData PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentLUTAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentLUTAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentLUTAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentLUTAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentLUTTextureAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentLUTTextureAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentLUTTextureAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentLUTTextureAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestAreaSelections "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestAreaSelections" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestAreaSelections.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestAreaSelections PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestValuePassFloatingPoint "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestValuePassFloatingPoint" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestValuePassFloatingPoint.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestValuePassFloatingPoint PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-otherCoordinate "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "otherCoordinate" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-otherCoordinate PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-FrustumClip "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "FrustumClip" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/FrustumClip.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-FrustumClip PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-Mace "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "Mace" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/Mace.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-Mace PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-RGrid "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "RGrid" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/RGrid.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-RGrid PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestActor2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestActor2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestActor2D.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestActor2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestActor2DTextures "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestActor2DTextures" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestActor2DTextures.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestActor2DTextures PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestActorLightingFlag "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestActorLightingFlag" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestActorLightingFlag.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestActorLightingFlag PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestAnimationScene "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestAnimationScene" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestAnimationScene.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestAnimationScene PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestAssemblyBounds "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestAssemblyBounds" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestAssemblyBounds PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestBackfaceCulling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestBackfaceCulling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestBackfaceCulling.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestBackfaceCulling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestBareScalarsToColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestBareScalarsToColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestBareScalarsToColors.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestBareScalarsToColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestBlockOpacity "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestBlockOpacity" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestBlockOpacity.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestBlockOpacity PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorByCellDataStringArray "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorByCellDataStringArray" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestColorByCellDataStringArray.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorByCellDataStringArray PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorByPointDataStringArray "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorByPointDataStringArray" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestColorByPointDataStringArray.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorByPointDataStringArray PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorByStringArrayDefaultLookupTable "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorByStringArrayDefaultLookupTable" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestColorByStringArrayDefaultLookupTable.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorByStringArrayDefaultLookupTable PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorByStringArrayDefaultLookupTable2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorByStringArrayDefaultLookupTable2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestColorByStringArrayDefaultLookupTable2D.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorByStringArrayDefaultLookupTable2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorTransferFunction "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorTransferFunction" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorTransferFunction PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestColorTransferFunctionStringArray "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestColorTransferFunctionStringArray" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestColorTransferFunctionStringArray PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestDirectScalarsToColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestDirectScalarsToColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestDirectScalarsToColors.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestDirectScalarsToColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestDiscretizableColorTransferFunction "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestDiscretizableColorTransferFunction" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestDiscretizableColorTransferFunction PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestDiscretizableColorTransferFunctionStringArray "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestDiscretizableColorTransferFunctionStringArray" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestDiscretizableColorTransferFunctionStringArray PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestEdgeFlags "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestEdgeFlags" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestEdgeFlags.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestEdgeFlags PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestFollowerPicking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestFollowerPicking" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestFollowerPicking.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestFollowerPicking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGlyph3DMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapper2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapper2" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapper2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapperArrow "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapperArrow" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGlyph3DMapperArrow.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapperArrow PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapperMasking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapperMasking" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGlyph3DMapperMasking.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapperMasking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapperOrientationArray "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapperOrientationArray" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGlyph3DMapperOrientationArray.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapperOrientationArray PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGlyph3DMapperPicking "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGlyph3DMapperPicking" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGlyph3DMapperPicking.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGlyph3DMapperPicking PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestGradientBackground "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestGradientBackground" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestGradientBackground.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestGradientBackground PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestHiddenLineRemovalPass "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestHiddenLineRemovalPass" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestHiddenLineRemovalPass.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestHiddenLineRemovalPass PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestHomogeneousTransformOfActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestHomogeneousTransformOfActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestHomogeneousTransformOfActor.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestHomogeneousTransformOfActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestImageAndAnnotations "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestImageAndAnnotations" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestImageAndAnnotations.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestImageAndAnnotations PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestInteractorStyleImageProperty "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestInteractorStyleImageProperty" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestInteractorStyleImageProperty PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestInteractorTimers "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestInteractorTimers" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestInteractorTimers PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestLabeledContourMapper "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestLabeledContourMapper" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestLabeledContourMapper.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestLabeledContourMapper PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestLabeledContourMapperWithActorMatrix "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestLabeledContourMapperWithActorMatrix" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestLabeledContourMapperWithActorMatrix.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestLabeledContourMapperWithActorMatrix PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestPickingManager "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestPickingManager" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestPickingManager PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestManyActors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestManyActors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestManyActors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestMapVectorsAsRGBColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestMapVectorsAsRGBColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestMapVectorsAsRGBColors.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestMapVectorsAsRGBColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestMapVectorsToColors "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestMapVectorsToColors" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestMapVectorsToColors.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestMapVectorsToColors PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestOffAxisStereo "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestOffAxisStereo" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestOffAxisStereo.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestOffAxisStereo PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestOrderedTriangulator "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestOrderedTriangulator" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestOrderedTriangulator.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestOrderedTriangulator PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestOpacity "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestOpacity" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestOpacity.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestOpacity PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestOSConeCxx "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestOSConeCxx" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestOSConeCxx.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestOSConeCxx PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestPickTextActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestPickTextActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestPickTextActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestPointSelection "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestPointSelection" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestPointSelection PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestPolygonSelection "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestPolygonSelection" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestPolygonSelection.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestPolygonSelection PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestResetCameraVerticalAspectRatio "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestResetCameraVerticalAspectRatio" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestResetCameraVerticalAspectRatio.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestResetCameraVerticalAspectRatio PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestResetCameraVerticalAspectRatioParallel "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestResetCameraVerticalAspectRatioParallel" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestResetCameraVerticalAspectRatioParallel.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestResetCameraVerticalAspectRatioParallel PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestSplitViewportStereoHorizontal "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestSplitViewportStereoHorizontal" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestSplitViewportStereoHorizontal.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestSplitViewportStereoHorizontal PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTexturedBackground "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTexturedBackground" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTexturedBackground.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTexturedBackground PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTextureSize "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTextureSize" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTextureSize PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTextureRGBA "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTextureRGBA" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTextureRGBA.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTextureRGBA PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTextureRGBADepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTextureRGBADepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTextureRGBADepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTextureRGBADepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTilingCxx "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTilingCxx" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTilingCxx.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTilingCxx PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTransformCoordinateUseDouble "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTransformCoordinateUseDouble" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTransformCoordinateUseDouble.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTransformCoordinateUseDouble PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentImageActorAlphaBlending "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentImageActorAlphaBlending" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentImageActorAlphaBlending.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentImageActorAlphaBlending PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentImageActorDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentImageActorDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentImageActorDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentImageActorDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentLUTDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentLUTDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentLUTDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentLUTDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTranslucentLUTTextureDepthPeeling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTranslucentLUTTextureDepthPeeling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTranslucentLUTTextureDepthPeeling.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTranslucentLUTTextureDepthPeeling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTStripsColorsTCoords "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTStripsColorsTCoords" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTStripsColorsTCoords.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTStripsColorsTCoords PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTStripsNormalsColorsTCoords "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTStripsNormalsColorsTCoords" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTStripsNormalsColorsTCoords.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTStripsNormalsColorsTCoords PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTStripsNormalsTCoords "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTStripsNormalsTCoords" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTStripsNormalsTCoords.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTStripsNormalsTCoords PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestTStripsTCoords "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestTStripsTCoords" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestTStripsTCoords.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestTStripsTCoords PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-TestWindowToImageFilter "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "TestWindowToImageFilter" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/TestWindowToImageFilter.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-TestWindowToImageFilter PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-otherLookupTable "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "otherLookupTable" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-otherLookupTable PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-otherLookupTableWithEnabling "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "otherLookupTableWithEnabling" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-otherLookupTableWithEnabling PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-RenderNonFinite "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "RenderNonFinite" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/RenderNonFinite.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-RenderNonFinite PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
ADD_TEST(vtkRenderingCoreCxx-SurfacePlusEdges "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingCoreCxxTests" "SurfacePlusEdges" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Core/Testing/Data/Baseline/SurfacePlusEdges.png")
SET_TESTS_PROPERTIES(vtkRenderingCoreCxx-SurfacePlusEdges PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingCore")
