# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/Annotation/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/Annotation/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingAnnotationCxx-TestAxisActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestAxisActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestAxisActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestAxisActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestAxisActor2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestAxisActor2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestAxisActor2D.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestAxisActor2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestAxisActor3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestAxisActor3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestAxisActor3D.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestAxisActor3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestAxisActorText3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestAxisActorText3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestAxisActorText3D.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestAxisActorText3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestBarChartActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestBarChartActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestBarChartActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestBarChartActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCaptionActor2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCaptionActor2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCaptionActor2D.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCaptionActor2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestConvexHull2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestConvexHull2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestConvexHull2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCornerAnnotation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCornerAnnotation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCornerAnnotation.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCornerAnnotation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxes2DMode "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxes2DMode" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxes2DMode.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxes2DMode PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxes3 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxes3" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxes3.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxes3 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridAll "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesInnerGridAll" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesInnerGridAll.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridAll PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridClosest "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesInnerGridClosest" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesInnerGridClosest.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridClosest PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridFurthest "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesInnerGridFurthest" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesInnerGridFurthest.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesInnerGridFurthest PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesIntersectionPoint "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesIntersectionPoint" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesIntersectionPoint.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesIntersectionPoint PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesOrientedBoundingBox "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesOrientedBoundingBox" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesOrientedBoundingBox.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesOrientedBoundingBox PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesSticky "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesSticky" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesSticky.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesSticky PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesStickyCentered "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesStickyCentered" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesStickyCentered.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesStickyCentered PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithGridLines "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithGridLines" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithGridLines.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithGridLines PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithXInnerGrids "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithXInnerGrids" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithXInnerGrids.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithXInnerGrids PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithXInnerPolys "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithXInnerPolys" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithXInnerPolys.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithXInnerPolys PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithXLines "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithXLines" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithXLines.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithXLines PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithYInnerGrids "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithYInnerGrids" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithYInnerGrids.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithYInnerGrids PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithYInnerPolys "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithYInnerPolys" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithYInnerPolys.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithYInnerPolys PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithYLines "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithYLines" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithYLines.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithYLines PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithZInnerGrids "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithZInnerGrids" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithZInnerGrids.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithZInnerGrids PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithZInnerPolys "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithZInnerPolys" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithZInnerPolys.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithZInnerPolys PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestCubeAxesWithZLines "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestCubeAxesWithZLines" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestCubeAxesWithZLines.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestCubeAxesWithZLines PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestEmptyCornerAnnotation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestEmptyCornerAnnotation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestEmptyCornerAnnotation.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestEmptyCornerAnnotation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestLegendBoxActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestLegendBoxActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestLegendBoxActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestLegendBoxActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestLegendBoxActor2 "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestLegendBoxActor2" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestLegendBoxActor2.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestLegendBoxActor2 PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestLegendScaleActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestLegendScaleActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestLegendScaleActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestLegendScaleActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestPieChartActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestPieChartActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestPieChartActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestPieChartActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestPolarAxes "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestPolarAxes" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestPolarAxes.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestPolarAxes PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestScalarBar "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestScalarBar" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestScalarBar.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestScalarBar PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestScalarBarAboveBelow "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestScalarBarAboveBelow" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestScalarBarAboveBelow.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestScalarBarAboveBelow PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestSpiderPlotActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestSpiderPlotActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestSpiderPlotActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestSpiderPlotActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
ADD_TEST(vtkRenderingAnnotationCxx-TestXYPlotActor "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingAnnotationCxxTests" "TestXYPlotActor" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Annotation/Testing/Data/Baseline/TestXYPlotActor.png")
SET_TESTS_PROPERTIES(vtkRenderingAnnotationCxx-TestXYPlotActor PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingAnnotation")
