# CMake generated Testfile for 
# Source directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK/Rendering/Image/Testing/Cxx
# Build directory: /home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Rendering/Image/Testing/Cxx
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(vtkRenderingImageCxx-TestCellPickerImage "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestCellPickerImage" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestCellPickerImage.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestCellPickerImage PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperAlpha "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperAlpha" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperAlpha.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperAlpha PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperAlpha "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperAlpha" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperAlpha.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperAlpha PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperBackground "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperBackground" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperBackground.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperBackground PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperBackground "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperBackground" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperBackground.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperBackground PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperBorder "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperBorder" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperBorder.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperBorder PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperBorder "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperBorder" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperBorder.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperBorder PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperInterpolation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperInterpolation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperInterpolation.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperInterpolation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperInterpolation "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperInterpolation" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperInterpolation.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperInterpolation PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperOrient2D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperOrient2D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperOrient2D.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperOrient2D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperOffAxis "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperOffAxis" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperOffAxis.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperOffAxis PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageSliceMapperOrient3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageSliceMapperOrient3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageSliceMapperOrient3D.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageSliceMapperOrient3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperOrient3D "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperOrient3D" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperOrient3D.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperOrient3D PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageStack "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageStack" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageStack.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageStack PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
ADD_TEST(vtkRenderingImageCxx-TestImageResliceMapperSlab "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/bin/vtkRenderingImageCxxTests" "TestImageResliceMapperSlab" "-D" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData//Testing" "-T" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/Testing/Temporary" "-V" "/home/mike/PCL-Tests/meshGeneration/vtk/VTK-build/VTK-Release-build/ExternalData/Rendering/Image/Testing/Data/Baseline/TestImageResliceMapperSlab.png")
SET_TESTS_PROPERTIES(vtkRenderingImageCxx-TestImageResliceMapperSlab PROPERTIES  FAIL_REGULAR_EXPRESSION "(
|^)ERROR: " LABELS "vtkRenderingImage")
